services:
  - type: web
    name: chemical-equipment-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: equipment_visualizer.settings